# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0aeef465490d3f30b84c9ed54d117fb0f000e5f9b529eb43c982f61082539d64709b6c26ef75a11475d10319fac6f5e80089bca996e59e5814fc1986efb7c6

test:
  secret_key_base: 6fb851a4f4ddf5638655dbcb602c2c23e25a7e011a30e9f686dcb53cffaeee08572b808140fa9f202b53343ec3ad44b445003cae9c9545264484de8fa4d452ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
